/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'medina' at '11/09/17 09:06' with Gradle 3.2.1
 *
 * @author medina, @date 11/09/17 09:06
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
